### PR TITLE
Change to make address history sorted and deterministic

### PR DESCRIPTION
**Pull request by fireduck64**
This is running on ele-rsync.1209k.com.  I've also made a similar change to jelectrum for consistent behavior.

### CODE REVIEW

**Comment by ecdsa** [comment]
this might impact performance negatively

**Comment by fireduck64** [comment]
Having clients request the entire address history over and over again because the hashes don't match up might impact performance as well.  I am not a python expert but I think all we are adding is another list copy, the sort was already being done but then not having an effect used because of the set() call after it.

**Comment by kyuupichan** [comment]
ecdsa: electrum keeps redownloading my tx history from different servers, because they serve them in different orders.  This ordering needs to be well-defined so that hashes match the history stored locally.  

Have you not noticed long lists of [Synchronizer] receiving transaction history messages when electrum is started up? It's happening perhaps 40% of the time for me.

**Comment by ecdsa** [comment]
oh sorry, you're right; I was confused

**Comment by ecdsa** [comment]
it must be a regression that was introduced with the new storage data structure.
earlier versions of Electrum used to sort the history.

**Comment by kyuupichan** [comment]
Unfortunately I've just realized this doesn't help at all.

**Pull request merged**
