### PR TITLE
retry bitcoind before failing

### PR DESCRIPTION
**Pull request by shsmith**
retry bitcoind a few times before failing.
may prevent leveldb corruption following bitcoind (getfullblock) timeout
(see http://pastebin.com/pfj4tEZV)
also improve catchup logging

### CODE REVIEW

**Comment by ecdsa** [comment]
good find; I think indeed this situation might cause some corruption.

**Comment by ecdsa** [comment]
fixed it, thanks

**Comment by shsmith** [comment]
i think we would still benefit from at least one retry before disconnecting all sessions. a single timeout results in hundreds of sessions disconnecting and then flooding other servers. for example:

```
[13/07/2015-02:25:03] cannot reach bitcoind...
[13/07/2015-02:25:03] closing 379 sessions
[13/07/2015-02:25:03] closing 6 sessions
[13/07/2015-02:25:03] bitcoind is responding
```

**Comment by ecdsa** [comment]
hmm, why is bitcoind not responding on your system?

**Pull request closed without merging**
