### PR TITLE
Add IRC SSL and IP Binding

### PR DESCRIPTION
**Pull request by mlapaglia**
added SSL to IRC connections, as well as the ability to bind the IRC
client to a specific IP address

### CODE REVIEW

**Comment by EagleTM** [comment]
@ecdsa Probably good to merge, as SSL is used anyway for tcp, so no new dependency. Can't hurt to secure IRC communication.

**Comment by ecdsa** [comment]
@mlapaglia I sent you an email about relicensing. 
please answer!

**Comment by mlapaglia** [comment]
Sorry I can't find the email anymore. I approve of the license change.

**Comment by ecdsa** [comment]
ok, I sent it again. thanks!

**Pull request merged**
